#ifndef CONFIGURATION_INCLUDE_GUARD
#define CONFIGURATION_INCLUDE_GUARD

#cmakedefine CHUNK_SIZE @CHUNK_SIZE@
#cmakedefine ACCUMULATOR_CAPACITY @ACCUMULATOR_CAPACITY@
#cmakedefine USE_ICONV
#cmakedefine USE_ICU

#endif
