#ifndef CONFIGURATION_INCLUDE_GUARD
#define CONFIGURATION_INCLUDE_GUARD

#define CHUNK_SIZE @CHUNK_SIZE@
#define ACCUMULATOR_CAPACITY @ACCUMULATOR_CAPACITY@
#define PYTHON_EXECUTABLE @PYTHON_EXECUTABLE_ESCAPED@
#cmakedefine USE_ICONV
#cmakedefine USE_ICU

#endif
